/*
Stack Overflow

When the function keep calling itself repeatdly, it will end up reaching a max for the stack, and will
throw an error.

Usually it happens because some criteria to exit the function was never met, or because some value or 
connection (on a tree/graph) it is wrong or referencing herself.
*/